### ISSUE TITLE
テストコード

### ISSUE THREAD

**Issue by stakiran** [tritask/tritask-vscode#15]
lint にせよ refactoring にせよ、ガッと修正した後でも動くことをさっと確認したい。

## サマリー
- テストコード書くために、thenable なコードになっている必要があった（が全然なってなかった）
- 数日かけてガッツリやった
- mocha によるテストコードの仕組み自体はつくってある
- 続きは #20 で

## task
- [x] テストコード実行できるようにする
- [x] mocha で非同期テスト書けるようにする
- こっから https://github.com/tritask/tritask-vscode/tree/testcode で一通りやる
- [x] add でワンパス通してみる
- ==== テストコード書けないので thenable base に修正 ====
- [x] 1: 各関数および CursorMover を ~~thenable<T>~~`Promise<boolean>` で return させる
- [x] Promise<boolean> せざるをえない場所の対処
    - :rabbit: ~~気の所為ならそれでいい（Thenable<boolean>ベースの途中でPromise<boolean>になるからテストコードダメかもという懸念~~ Promise<boolean> に統一する。then() の中で resolve することで変換する
    - [x] `edit().then(){ この中で return false or true する場合}`
    - [x] endTask で、edit する前に end 不要で return する場合
- [x] 2: doSave に依存しているやつは全部 async funtion にして、await doSave() で待ち合わせる
- (ここができたら await 対応ワンパス)
- [x] 3: copyTask まわりを await で待ち合わせる
- ……

**Comment by stakiran** [comment]
どうやるんだろうなぁ。

やってることが基本的に

- helper.py 呼び出して trita ファイルいじらせる
- vscode.window.activeTextEditor 使ってテキストやカーソルを取得したり動かしたり

で、unittest 書きづらいんだよなぁ。

vscode.window.activeTextEditor にモック差し込んだりとかできたりする？

**Comment by stakiran** [comment]
いや、普通に「VSCode ウィンドウ新たに立ち上げて、a.trita 開いて、所定の操作させて、**最後にカーソル位置やテキストの内容をgetしてassertする**」

↑ これできる気がする

**Comment by stakiran** [comment]
テストコード実行するたびにいちいちウィンドウ新たに立ち上がる感じ（GUIテスト）になるけど、それでも手作業よりははるかに良い。

**Comment by stakiran** [comment]
## 書くとしたら
日付が変わると並び順が変わるので、テスト時に毎回ゼロからデータをつくるようにする

- add する
- (addの結果をテストする)
- copy する
- (copyの結果をテストする)
- ……
- sort する
- (sortの結果をテストする)
- カーソル移動系操作1
- (カーソル移動系操作1の結果をテストする)
- ……

**Comment by stakiran** [comment]
## mocha 思い出す
[mocha における describe it before beforeEach after afterEach の実行順序 - Qiita](https://qiita.com/sta/items/2c89af1e05202fb76b96)

## テストコードは既に yo code のおかげで実行できるようになってる
- src\test\suite\extension.test.ts これが実行されるようになってる
    - 正式には ` glob('**/**.test.js'` なので、src 配下に *.test.js 置いたら全部実行される
- launch の Extension Tests を実行すれば良い
- 実行すると
    - 1: vscode window 新しく立ち上がる
    - 2: テストコード走る
    - 3: デバッグコンソールに結果出る
    - 4: テスト終わったら window もばいちゃ

## 少しおためし


```ts
import * as assert from 'assert';
import { describe, before, after, beforeEach, afterEach, it } from 'mocha';

import * as vscode from 'vscode';

// import * as myExtension from '../extension';

suite('Extension Test Suite', () => {
	before(() => {
		vscode.window.showInformationMessage('Start all tests.');
	});

	test('Sample test', () => {
		assert.strictEqual(-1, [1, 2, 3].indexOf(5));
		assert.strictEqual(-1, [1, 2, 3].indexOf(0));
	});
});

describe('describe1', () => {
	before(() => {
		console.log('before')
	});

	after(() => {
		console.log('after')
	});

	beforeEach(() => {
		console.log('before')
	});

	afterEach(() => {
		console.log('after')
	});

	it('test1', () => {
		assert.strictEqual(1, 100-98-1);
	});

	it('test2', () => {
		assert.strictEqual(2, 100-98);
	});

});

describe('describe2', () => {
	it('test3', () => {
		assert.strictEqual(1, 100-98-1);
	});
});
```

```terminal
  Extension Test Suite
    √ Sample test
  describe1
2
before
    √ test1
after
before
    √ test2
2
after
  describe2
    √ test3
  4 passing (79ms)
```

**Comment by stakiran** [comment]
## suite と test って何？describe や it じゃダメなの？

**Comment by stakiran** [comment]
[Testing Extensions | Visual Studio Code Extension API](https://code.visualstudio.com/api/working-with-extensions/testing-extension)

記述なさそう。たぶん単に「suite がスイート表してて、テストケースは test が使えるよ（mochaデフォの describe と it はわかりづらいけどこれならわかりやすいやろ？）」ってことかな

**Comment by stakiran** [comment]
うん、suite は describe の、test は it のシンタックスシュガーっぽい

**Comment by stakiran** [comment]
## chaiは？
まあ assert あるし、いったんこれでいいか

**Comment by stakiran** [comment]
## テストコードから test.trita(空ファイル) を開くには？

**Comment by stakiran** [comment]
[VS Code API | Visual Studio Code Extension API](https://code.visualstudio.com/api/references/vscode-api)

vscode.window.openNewFile() ← こんなんがあるはず

**Comment by stakiran** [comment]
開いたかどうか見れないんだが。

```
function pause(){
	const commandLine = "pause"
	exec(commandLine, (err) => {
		if(err){
			console.log(err);
		}
	});
}

function sleep(msec: number){
	setTimeout(() => {}, msec)
}
```

pause でも setTimeout でも構わず終了しやがる

**Comment by stakiran** [comment]
あとかれんとでぃれくとりもわからん。

```
		console.log(vscode.workspace.name)
		console.log(vscode.workspace.workspaceFolders)
```

undefined だし。まず workspace folder を開く必要がある？

**Comment by stakiran** [comment]
https://code.visualstudio.com/api/references/vscode-api#TextDocument

activeTextEditor.document.fileName で「untitled 1」まで取れた。

が、ディレクトリはないっぽいな。

今が src/test/suite/extension.test.ts なんだが、src を得るにはどうしたらいいんだ？

**Comment by stakiran** [comment]
```
		console.log(vscode.workspace.name)
		console.log(vscode.workspace.workspaceFolders)
		console.log(IDE.getEditor().document.fileName)
		console.log(vscode.workspace.asRelativePath('123')) // workspace folder とやらがないから 123 がそのまま帰る
```

その workspace folder のパスが知りたいんやが

**Comment by stakiran** [comment]
console.log(vscode.env.appRoot)

ちゃう。`c:\Program Files\Microsoft VS Code\resources\app` が出た。

……いや、実行時にここに各種ファイルがコピーされてくるから、ここ基点で進めればええってこと？

**Comment by stakiran** [comment]
いや、違うね

**Comment by stakiran** [comment]
> 今が src/test/suite/extension.test.ts なんだが、src を得るにはどうしたらいいんだ？

これが欲しい。src/test/suite/test.trita を開きたいんですけども……

**Comment by stakiran** [comment]
```
		console.log(vscode.env.appRoot)
		console.log(vscode.env.shell)
		console.log(vscode.workspace.name)
		console.log(vscode.workspace.workspaceFile)
		console.log(vscode.workspace.workspaceFolders)
		console.log(IDE.getEditor().document.fileName)
		console.log(IDE.getEditor().document.uri.fsPath)
		console.log(vscode.workspace.asRelativePath('123'))
```

マジで正解どれなん……？

**Comment by stakiran** [comment]
[javascript - VS Code extension - get full path - Stack Overflow](https://stackoverflow.com/questions/39569993/vs-code-extension-get-full-path)

ググってもこれしか出てこない。

その workspace folder が空なんですよ。

**Comment by stakiran** [comment]
.../src/test/suite/extension.test.ts を実行してるんだから、.../src/test/suite/ を得る手段が絶対あるはずだと思うんだが

**Comment by stakiran** [comment]
https://code.visualstudio.com/api/working-with-extensions/testing-extension#the-test-script

**Comment by stakiran** [comment]
path さんでしたか

> console.log(path.resolve(__dirname))

> d:\work\github\stakiran_sub\tritask-vscode-PUBLIC\tritask-language-features\out\test\suite

**Comment by stakiran** [comment]
だが out 側に test.trita などテスト用ファイルがない

**Comment by stakiran** [comment]
[node.js で絶対パスや相対パスを取得する方法 npm __dirname](https://gist.github.com/uupaa/da42698d6b2d2cbb3cca)

**Comment by stakiran** [comment]
## やっとできた
![image](https://user-images.githubusercontent.com/23325839/102002929-b47b9300-3d44-11eb-8048-966464c77bc4.png)

**Comment by stakiran** [comment]
```ts
import * as path from 'path'

class Path {
	static get _entrypoint(){
		// __dirname には現在実行中のソースコードが格納されているディレクトリ.
		// node.js の動作.
		// src/test/suite/test.ts の場合, out/test/suite になる
		return path.resolve(__dirname)
	}

	static get root(){
		const defaultRoot = this._entrypoint
		return path.resolve(defaultRoot, '..', '..', '..', 'src', 'test', 'suite')
	}
}
```

わりかししんどい。 Path.root にあたるパスを一発で取得できるシステム変数があってもばちあたらんと思うが

**Comment by stakiran** [comment]
## ソースコード extension.ts を import する方法がわからん……

```
import * as tritask from '../../../src/extension'
```

これだと型定義なくてダメ。

![image](https://user-images.githubusercontent.com/23325839/102003093-4637d000-3d46-11eb-9389-992bd2f5761b.png)

```
const tritask = require('../../../src/extension.ts')
```

これだと SyntaxError: Cannot use import statement outside a module

**Comment by stakiran** [comment]
```ts
// import * as myExtension from '../extension';
```

yo code のテンプレはこれを出してる

**Comment by stakiran** [comment]
ぐぐると「型が存在してない」的な内容がヒットする……

![image](https://user-images.githubusercontent.com/23325839/102003117-93b43d00-3d46-11eb-82cb-7aee6015a269.png)

ちゃんと定義してんだけどなぁ。それとも `<string>SELF_EXTENSION_ID=` みたいにしてないから認識されてない？

**Comment by stakiran** [comment]
typescript わからんからわからん

**Comment by stakiran** [comment]
あ、export してないからだ

**Comment by stakiran** [comment]
あと console.log がダメ

```
Error: Cannot find module '../../../src/extension'
Require stack:
……
```

**Comment by stakiran** [comment]
ダメだぁ、歯が立たない。付け焼き刃だときっついなぁ。 https://code.visualstudio.com/api/references/vscode-api 程度の情報量だとわからん

**Comment by stakiran** [comment]
extention.ts

```
 export {
	 getSelfDirectory
 }
 ```

extention.test.ts

```
import * as tritask from '../../../src/extension';

		tritask.getSelfDirectory()

```

これでエラー無く通ったけど、デバッグコンソールに何も表示されなくなった……

**Comment by stakiran** [comment]
いや、エラー出てた（出たり出なかったりする）

```
Error: Cannot find module '../../../src/extension'
Require stack:
- d:\work\github\stakiran_sub\tritask-vscode-PUBLIC\tritask-language-features\out\test\suite\extension.test.js
- d:\work\github\stakiran_sub\tritask-vscode-PUBLIC\tritask-language-features\node_modules\mocha\lib\mocha.js
- d:\work\github\stakiran_sub\tritask-vscode-PUBLIC\tritask-language-features\node_modules\mocha\index.js
- d:\work\github\stakiran_sub\tritask-vscode-PUBLIC\tritask-language-features\out\test\suite\index.js
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js
```

**Comment by stakiran** [comment]
わけわかんね

**Comment by stakiran** [comment]
https://code.visualstudio.com/api/references/vscode-api さんが  import * as myExtension from '../extension の myExtension を使う例を書いてくれたらありがたいんだが

**Comment by stakiran** [comment]
どっか拡張機能のソースでも漁るかいね

**Comment by stakiran** [comment]
vscode-eslint

https://github.com/microsoft/vscode-eslint/blob/master/client/src/tests/glob.test.ts

**Comment by stakiran** [comment]
- vscode-eslint/client/src/tests/glob.test.ts 
    - `import { convert2RegExp } from '../utils';`

```
export function convert2RegExp(pattern: string): RegExp | undefined {
	const separator = process.platform === 'win32' ? '\\\\' : '\\/';
	const fileChar = `[^${separator}]`;
	function convertNode(node: Node): string {
```

なるほど、外から使わせたい関数は export つけて定義しちゃうのか（まあ当たり前か

**Comment by stakiran** [comment]
ダメっす

```
import { getSelfDirectory } from '../../../src/extension';

		getSelfDirectory()
```

> Error: Cannot find module '../../../src/extension'

これが出る

**Comment by stakiran** [comment]
## Cong! :smile:

```
import { getSelfDirectory } from '../../extension'; // ★ ../../../src/extension だとなぜかダメ（VSCode 上ではエラー出なかったのに）
		console.log(getSelfDirectory())

```

`..` 入りの相対パスは「最低限の長さ」で書くべきってことかな。

たぶん node,js だか vscode だがのそのへんのパスの組み立て処理が（無駄に `..` を重ねる書き方に）対応してない。

- :o: `../../extension`
- :x: ` ../../../src/extension`
    - 上と同じ意味だが、内部的な組み立て処理がなんかミスって正しく解決できていない（のだと思われる
    - もっというと
        - **VSCodeエディタ上では解決できてる** が、テストコード実行時は解決できてない
        - :rabbit: そりゃハマるンゴ……

**Comment by stakiran** [comment]
https://github.com/tritask/tritask-vscode/commit/5aa2f7b0bd3406a28046cca511ee32501bd9d671

ほい、テスト用ファイル開くワンパスできた（長かった……

**Comment by stakiran** [comment]
vscode.workspace.openTextDocument(TESTEE_FULLLPATH) 失敗したときってどうやって検出するん？

Thenable とのことだが、catch() 書くとエラーになる。

**Comment by stakiran** [comment]
ああ、そうだった、普通に onfulfilled と onrejected を並べて定義すればいいだけだった

![image](https://user-images.githubusercontent.com/23325839/102003478-65852c00-3d4b-11eb-9572-43dfb164d647.png)

then().catch() の書き方しか使ってなかったから

**Comment by stakiran** [comment]
非同期の書き方しないとあかんな

**Comment by stakiran** [comment]
https://code.visualstudio.com/api/working-with-extensions/testing-extension#custom-setup-with-vscodetest

```
async function main() {
  try {
    // ★ここでテストコードのファイルパスつくって
    const extensionDevelopmentPath = path.resolve(__dirname, '../../../');
    const extensionTestsPath = path.resolve(__dirname, './suite/index');
    const vscodeExecutablePath = await downloadAndUnzipVSCode('1.40.1');
    const cliPath = resolveCliPathFromVSCodeExecutablePath(vscodeExecutablePath);

……

    // ★ここで指定して
    await runTests({
      // Use the specified `code` executable
      vscodeExecutablePath,
      extensionDevelopmentPath,
      extensionTestsPath
    });
  } catch (err) {
    console.error('Failed to run tests');
    process.exit(1);
  }
}

// ★async function を呼び出す形にする
main();
```

**Comment by stakiran** [comment]
いや、これは単に main() の中が終わるまで待ってるってだけか

**Comment by stakiran** [comment]
suite() や test() 使ってる中で、async await で制御していきたいんだが

**Comment by stakiran** [comment]
mocha + 非同期をやらなあかんってことだね

**Comment by stakiran** [comment]
[\[nodejs\] mochaで非同期が絡む処理のテストを書いてハマったこと - Qiita](https://qiita.com/mktoho-n/items/587ae420df0331df076a)

んー、it の中に promise chain 書きたくないな

**Comment by stakiran** [comment]
![image](https://user-images.githubusercontent.com/23325839/102003655-25bf4400-3d4d-11eb-803c-f5df4e188803.png)

とりあえずテスト用ファイル開けなかった場合に、テストそれ以上進むのやめさせたい。

これを実現できれば、非同期をマスターしたも同然。

**Comment by stakiran** [comment]
一番楽なのは、describe と it を全部 await 的に順に実行させるような書き方なんだが。

**Comment by stakiran** [comment]
[\[Node\] Mochaで非同期処理の例外ハンドリング | Today's Commit](https://t-kojima.github.io/2018/07/16/0027-mocha-async-error-handling/)

いけた。

> mocha は Promise を return すると、mocha はちゃんと Promise のテストであると判断して処理してくれる。

**Comment by stakiran** [comment]
> Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

**Comment by stakiran** [comment]
[mochaによる非同期のテストの書き方 - 30歳からのプログラミング](https://numb86-tech.hatenablog.com/entry/2017/04/02/212259)

- it に done を渡して、done() を call しておしまいの形にする
- done を使わず、it から return する promise オブジェクトの then の中でアサートする

どっちかの方法になるっぽいな

**Comment by stakiran** [comment]
```ts
suite('describe1', () => {
	before(() => {
		const promise = IDE.openTesteeFile()
		return promise.then(
			(doc: vscode.TextDocument) => {
				return doc // ★こいつを次の test に渡したいんだが、
			},
			(err) => {
				console.log(err)
				assert.fail('テスト用ファイルをopenできませんでした.')
			}
		)
	});

	after(() => {
	});

	test('test1', (done) => {
		assert.strictEqual(1, 100-98-1);
		console.log(done) // ★なんかmocha的には Done 関数が入るっぽいのよね（でも debug console には null と出る）
		done() // ★そしてこれ呼び出さないと Error: Timeout of 2000ms exceeded.  になるんだよね……
	});

});
```

## 🤔

**Comment by stakiran** [comment]
どう書けばいいんだ……

test1 から doc にアクセスできたらほぼゴール見えてるんだが……

**Comment by stakiran** [comment]
global に「doc を持ってる奴」をつくって、test() からはそいつにアクセスする？行儀悪いけど

before や test で promise 返したとすると、await 的な順番待ちも担保されてるからいけそうではあるが……

**Comment by stakiran** [comment]
![image](https://user-images.githubusercontent.com/23325839/102004003-df1f1900-3d4f-11eb-8d7d-b78635670dba.png)

どう書けばいいんだっけ

**Comment by stakiran** [comment]
[How to initialize an object in TypeScript - Stack Overflow](https://stackoverflow.com/questions/52616172/how-to-initialize-an-object-in-typescript)

class で定義しないとダメね。TestData.document の部分をこの形で型指定する文法がたぶんない

**Comment by stakiran** [comment]
## cong!

```ts
class TestData {
	static document: vscode.TextDocument;
}

suite('describe1', () => {
	before(() => {
		const promise = IDE.openTesteeFile()
		return promise.then(
			(doc: vscode.TextDocument) => {
				TestData.document = doc
			},
			(err) => {
				console.log(err)
				assert.fail('テスト用ファイルをopenできませんでした.')
			}
		)
	});

	after(() => {
	});

	test('test1', (done) => {
		assert.strictEqual(1, 100-98-1);
		console.log(TestData.document)
		done()
	});

});
```

**Comment by stakiran** [comment]
ソースに勉強ノート書いちゃったけど、

```ts
// ここで採用している mocha + 非同期テストの書き方.
// - suite と test を使う.
//   - suite は describe, test は it の糖衣構文(たぶん)
//   - わかりやすいネーミングだと思うので採用
// - before や test の中では promise object を返す.
//   - これにより, (当該非同期処理が終わるまで)次の test に行くのを待たせることができる
//   - (mocha 側が await 的なのを頑張ってくれてる)
// - 必要なデータは TestData でやりとりする.
//   - 前の test で return した promise object を, 次の test は受け取れないため.
// - テストコードの終わりでは done() する
//   - これしないと Error: Timeout of 2000ms exceeded. になる
//   - mocha 曰く
//     - 非同期処理がいつ終わるかわからん
//     - デフォではタイムアウト 2000ms にしてます( Error: Timeout of 2000ms exceeded. を出します
//     - いつ終わるかわからんけど、いつか終わる ← これできないと困るでしょ？
//       - だったら done() を使ってね
//       - done は test(), もっというと it() に渡しますんで
```

こういうことやよね？

**Comment by stakiran** [comment]
## test.trita 読み込んだ状態

```
Object
uri:Object
fileName:"d:\work\github\stakiran_sub\tritask-vscode-PUBLIC\tritask-language-features\src\test\suite\test.trita"
isUntitled:false
languageId:"tritask"
version:1
isClosed:false
isDirty:false
eol:2
lineCount:1
```

**Comment by stakiran** [comment]
あー、実装側で promise 返してないからダメかも……

**Comment by stakiran** [comment]
```ts
export function addTask(){
	const editor = getEditor();
	const todayString = DateTimeUtil.todayString();
	const inserteeString = `${EMPTYSORTMARK} ${todayString} ${EMPTYDOW} ${EMPTYTIME} ${EMPTYTIME} \n`;
	const inserteePos = CursorPositioner.linetop();
	const f = function(editBuilder: vscode.TextEditorEdit): void{
		editBuilder.insert(inserteePos, inserteeString);
	}
	editor.edit(f);

	CursorMover.golinetop().left();
}
```

これだと（ edit が終わる前に）終了してしまう

**Comment by stakiran** [comment]
全部作り直しになってまう……

**Comment by stakiran** [comment]
## とりあえず promise 返すようにして

```ts
export function addTask(){
	const editor = getEditor();
	const todayString = DateTimeUtil.todayString();
	const inserteeString = `${EMPTYSORTMARK} ${todayString} ${EMPTYDOW} ${EMPTYTIME} ${EMPTYTIME} \n`;
	const inserteePos = CursorPositioner.linetop();
	const f = function(editBuilder: vscode.TextEditorEdit): void{
		editBuilder.insert(inserteePos, inserteeString);
		CursorMover.golinetop().left();
	}
	return editor.edit(f);
}
```

**Comment by stakiran** [comment]
- 1: f の中では何を返すべきだろうか
- 2: CursorMover が `vscode.commands.executeCommand("cursorLineStart");` みたいな感じで、これも thenable なので修正が要る

1 は

- 基本的に regiseterd command 呼んで終わり、だからぶっちゃけ何も要らない
- テストコード側で何かしたいなら何か入れてもいいが、TextEditor は別手段で取れるから別に要らない
- 一部コマンド(copyTask)は、他のタスクから呼ばれてることがらう(EndTaskはCopyTask呼んでる）
    - これは promise chain で繋ぐのがキレイ
    - copyTaskが「コピー後にカーソル動かしたいなら "カーソル動かす処理書いたコールバック" を与えよ」となってる

2 は現状ちょっとひどいので、

```ts
class CursorMover {
	static golinetop() {
		vscode.commands.executeCommand("cursorLineStart");
		return this;
	}
```

どうなおそうかん

**Comment by stakiran** [comment]
とりあえずブランチ壊したくないので、別の切って、そっちで一通り作り直してしまおうか。

**Comment by stakiran** [comment]
```ts
	const f = function(editBuilder: vscode.TextEditorEdit): void{
		editBuilder.insert(inserteePos, inserteeString);
		CursorMover.golinetop().left();
	}
	return editor.edit(f);
```

edit に渡すコールバックは void 返すやつだった。呼び出し元では、

```ts
	test('add task', () => {
		const promise = addTask()
		return promise.then(
			(args) => {
				const lineCount = TestData.document.lineCount
				console.log(args) //true ★なので成否が返ってくるのかな？
				//assert.strictEqual(lineCount, 2)
			}
		)
	});
```

うん、

> Thenable<boolean> | A promise that resolves with a value indicating if the edits could be applied.

とありますね

**Comment by stakiran** [comment]
## 反映されない問題はこうだった
- :x: TextDocument の中身はリアクティブに更新される
- :o: 更新後の値がほしければ、常に getEditor() で最新の ActiveTextEditor を取得しなさい

**Comment by stakiran** [comment]
## どこまでテストするかだなぁ
- 1 ファイルの中身（正しくデータの操作がされているか）
- 2 カーソル位置（正しい位置に動くか）

2 はだるそうなのでいったんなし。

1 だけあれば回帰テストはいける。

**Comment by stakiran** [comment]
```
addtask
addinbox
copytask
starttask
endtask

dosort
dosave

dorepeat if possible
walk
walk +1
walk to today

simple completion
jump to stariting
jump to today todo
jump to next
jump to prev
```

**Comment by stakiran** [comment]
start task done

**Comment by stakiran** [comment]
## :sob: endTask 以降がマジで難しい
戻り値何も考えずにつくってるから、thenable で返さないといけないようにするのがパッと見てできん

**Comment by stakiran** [comment]
```
	if(isNotStarted){
		return  Promise.resolve(false);
	}
```

Promise と Thenable は違うわけだが、Thenable はどうやって定義すればいいの？

……たぶん想定されてないんだよなぁ。

**Comment by stakiran** [comment]
endTask

```ts
export function endTask(){
	// s  e  >DoEnd>  s  e
	// -------------------
	// x  x           x  x    Invalid. start してないので end しない.
	// o  x           o  o    OK. 普通に end する.
	// o  o           o  x    OK. トグルで end をやめる.
	// x  o           -  -    Don't care.
	//
	// x  x から x  o に至れないので x  o の時は想定していない.
	// 今のコードだと end しない挙動になるが, 特に問題はないのでこのままで.

	const editor = getEditor();
	const doc = editor.document;
	const currentLine = doc.lineAt(CursorPositioner.current()).text;

	const currentStartTimeValue = currentLine.substr(POS_STARTTIME, LEN_TIME);
	const isNotStarted = currentStartTimeValue == EMPTYTIME;
	if(isNotStarted){
		return;
	}

	const currentEndTimeValue = currentLine.substr(POS_ENDTIME, LEN_TIME);
	const isDoneNewly = currentEndTimeValue == EMPTYTIME;
	const shouldCopyBecauseRepeat = currentLine.indexOf("rep:") != -1;

	let afterStringForEndTime = EMPTYTIME;
	if(isDoneNewly){
		afterStringForEndTime = DateTimeUtil.nowtimeString();
	}
	const endTimeRange = CursorPositioner.rangeBetweenEndTime()
	const endTimeBuilder = function(editBuilder: vscode.TextEditorEdit): void{
		editBuilder.replace(endTimeRange, afterStringForEndTime);
	}	
	const endTimePromise = editor.edit(endTimeBuilder);

	const functionAfterCopy = () => {
		CursorMover.golineend();
		doRepeatIfPossible();
	}

	endTimePromise.then(
		(isSucceedEdit) => {
			if(isSucceedEdit && isDoneNewly && shouldCopyBecauseRepeat){
				copyTask(functionAfterCopy);
			}
		}
	)
}
```

**Comment by stakiran** [comment]
- isnotstarted で return している
- editor.edit で endtime 記入
- endtime 記入後の then で copyTask
    - copyTask に渡してる golineend と doRepeatIfPossible() も非同期

ぐちゃぐちゃすぎる……ｗ

**Comment by stakiran** [comment]
copyTask

```ts
function copyTask(cursorMoverAfterCopy: any){ // eslint-disable-line  @typescript-eslint/no-explicit-any
	const editor = getEditor();
	const doc = editor.document;
	const currentLine = doc.lineAt(CursorPositioner.current()).text;
	const inserteeString = `${currentLine}\n`;
	const inserteePos = CursorPositioner.linetop();

	// 挿入後は現在行位置に「挿入した行」が来るため
	// 「挿入前における現在行位置」をそのまま使うだけで
	// 挿入した行に対する操作を行える.
	//
	//               line[x-1]
	// aaaaaaaIaa    line[x]
	//               line[x+1]
	// 
	//               line[x-1]
	// aaaaaaaIaa    line[x]    <== 挿入された行. x行目で変わらずアクセスできる.
	// aaaaaaaIaa    line[x+1]
	const startpos = CursorPositioner.startOfTimeFields();
	const endpos = CursorPositioner.endOfTimeFields();
	const replaceeRange = new vscode.Range(startpos, endpos);
	const afterString = `${EMPTYTIME} ${EMPTYTIME}`;

	// insert: 現在行を複製する.
	// replace: 複製した行の開始/終了時刻をクリアする(複製後は todo task として扱いたいはず).
	const f = function(editBuilder: vscode.TextEditorEdit): void{
		editBuilder.insert(inserteePos, inserteeString);
		editBuilder.replace(replaceeRange, afterString);
	}
	const promise = editor.edit(f);
	promise.then(
		(isSucceedEdit) => {
			if(!isSucceedEdit){
				return;
			}
			if(cursorMoverAfterCopy === undefined){
				return;
			}
			cursorMoverAfterCopy();
		}
	)
}
```

**Comment by stakiran** [comment]
- edit で insert と replace している
- edit 後の then で、呼び出し元から渡されたコールバックを実行している
    - コールバックがない or edit 失敗時 → return void
    - コールバックがある → それを呼ぶ(return void)

copyTask の呼び出し元は二つあって、

endTask さん

```ts
	const functionAfterCopy = () => {
		CursorMover.golineend();
		doRepeatIfPossible();
	}
```

copyTask のエントリポイント

```ts
	const task_copy = vscode.commands.registerCommand('tritask.task.copy', () => {
		const callbackAfterCopy = CursorMover.golineend;
		copyTask(callbackAfterCopy);
	});
```

**Comment by stakiran** [comment]
CursorMover.golineend

```ts
class CursorMover {
	static golineend() {
		vscode.commands.executeCommand("cursorLineEnd");
		return this;
	}
```

CursorMover 自体を return している(promise じゃない）

**Comment by stakiran** [comment]
dorepeat if possible

```ts
function doRepeatIfPossible(){
	const editor = getEditor();
	const curPos = CursorPositioner.current();
	const doc = editor.document;
	const currentLine = doc.lineAt(curPos).text;
	if(currentLine.indexOf("rep:") == -1){
		return;
	}

	const curLineNumber = curPos.line;
	const commandLine = `${getHelperCommandline()} -y ${curLineNumber} --repeat`;
	console.log(`Repeat: "${commandLine}"`);

	doSave();

	exec(commandLine, (err) => {
		if(err){
			console.log(err);
		}
	});
}
```

- これは helper から実行してるだけ

do save

```ts
function doSave(){
	const editor = getEditor();
	const doc = editor.document;

	// 変更が無い状態(not dirty)で save() すると failed になるので防止.
	if(!doc.isDirty){
		return;
	}

	const promise = editor.document.save();
	promise.then((result) =>{
		if(!result){
			abort("Failed to save()");
			throw new Error();
		}
	});
}
```

-  非同期の save をしている（けど return してない）

**Comment by stakiran** [comment]
## :sob: これはダメだ……ちょっと書き換えて済むレベルじゃない……
一から書き直した方が良いかもしれん

**Comment by stakiran** [comment]
## 依存関係
- copyTask
    - cursorMoverAfterCopy
- endTask
    - copyTask
        - CursorMover.golineend
        - doRepeatIfPossible
            - doSave
- doSort
    - doSave
- doRepeatIfPossible
    - doSave

**Comment by stakiran** [comment]
どうすべきか？

- どの操作も promise(というかThenable) を return させる
- テストコード側で「処理が全部終わるまで待てる」ように、promise chain or await list で実装する
    - :rabbit: ここがイメージわかんなぁ

**Comment by stakiran** [comment]
```ts
endTask(){
    // ……
    // ★ここどう書けばいい？ copyTask, golineend, do repeat 順に実行する
    // ……
    return thenable_boolean_object
}
```

**Comment by stakiran** [comment]
`save(): Thenable<boolean>` だから doSave は問題ない

**Comment by stakiran** [comment]
`executeCommand<T>(command: string, ...rest: any[]): Thenable<T | undefined>` だから golinetop（などカーソル移動系）も問題ない

**Comment by stakiran** [comment]
async function endTask(){ } で良い？

activate() の

```ts
	const task_end = vscode.commands.registerCommand('tritask.task.end', () => {
		endTask();
	});
```

ここが async に対応してるか心配なんだが

**Comment by stakiran** [comment]
問題なさそう。

ならいけるね

**Comment by stakiran** [comment]
## 🏃 ガッと修正する感じになるぞ
- 1: 各関数および CursorMover を thenable<T> で return させる
- 2: doSave に依存しているやつは全部 async funtion にして、await doSave() で待ち合わせる
- (ここができたら await 対応ワンパス)
- 3: copyTask まわりを await で待ち合わせる
- ……

ここまでいけばキレイな非同期コードになってるはず

**Comment by stakiran** [comment]
さあてと、やりますか 🏃 🏃

**Comment by stakiran** [comment]
抜本的修正なのでブランチ切った方が良い？

メモだけ: https://github.com/tritask/tritask-vscode/commit/48e1db5399a7f46de919506a401508e282cbb768

**Comment by stakiran** [comment]
1h でワンパス通します

2020/12/14 19:55:23

ready go!

2020/12/14 21:18:24 終わったの addTask だけ。まあそうスイスイとはいきませんよね

**Comment by stakiran** [comment]
## くせもの

```ts
class CursorMover {
	static golinetop() {
		return vscode.commands.executeCommand("cursorLineStart");
	}

	static golineend() {
		return vscode.commands.executeCommand("cursorLineEnd");
	}

	static left() {
		return vscode.commands.executeCommand("cursorLeft");
	}

	static up() {
		return vscode.commands.executeCommand("cursorUp");
	}
```

こいつらが Thenable<unknown> を返しやがるせいで、Thenable<boolean> たちと共存できない（chain できない）……

かといって vscode.Selection で up や down を再現するのは地獄

**Comment by stakiran** [comment]
いや、いけるか。

**Comment by stakiran** [comment]
いや、ダメ。

- left の場合、「行頭にいる時に行末に移動する」みたいなケースも全部対応しなきゃいけない
- up の場合、「前行が現在行より短い場合に、機械的に前行の同じ列、とできない（そんな列はない）」みたいなケースも対応が必要

えぐそう

**Comment by stakiran** [comment]
up はつかってなかったから消した

**Comment by stakiran** [comment]
add 後のカーソル位置は、

```
……I……
```

↓

```
(追加された行)
……I……
```

つまり1行だけ下にずれる

**Comment by stakiran** [comment]
move は left() ではなく、「前の行の pos_description」が正しい。

つまり left() 要らん

left() 実装マジエグかったので助かるンゴ……

```ts
	static left(): vscode.Position {
		const editor = getEditor();
		const curPos = editor.selection.active;

		let newY = curPos.line;
		let newX = curPos.character;

		const isLineTop = newX == 0
		const isNotLineTop = !isLineTop
		const isFirstLine = newY == 0
		const isNotFirstLine = !isFirstLine

		if(isLineTop && isNotFirstLine){
			const prevLinePos = curPos.with(newY - 1, newX)
			const doc = editor.document
			const prevLine = doc.lineAt(prevLinePos).text;
			const prevLineLength = prevLine.length
			newY = newY - 1
			newX = prevLineLength
		}else if(isLineTop && isFirstLine){
			// pass
		}else if(isNotLineTop){
			newX = newX - 1
		}

		return curPos.with(newY, newX);
	}
```

**Comment by stakiran** [comment]
## endTask の戻り値の型を Thenable<boolean> か Promise<boolean> にしたひ……
![image](https://user-images.githubusercontent.com/23325839/102144961-c460b780-3ea9-11eb-8c97-0140cbef8cf7.png)

が、少なくとも **処理不要時の return で Promise.resolve() するしかない** ので  Promise<boolean> にするしかない。（Thenable オブジェクトはつくる手段がない）

ってことは、今 Thenable<boolean> 返すやつは、then() で Promise<boolean> 返すようにする必要がある。

```ts
	return editor.edit(f);
```

↓

```ts
	return editor.edit(f).then(()=>{return Promise.resolve(true)})
```

みたいな

**Comment by stakiran** [comment]
重くなってきたので移動する

#20 へ
